dBildungsplattform/dbp-github-workflows

- .github/workflows/chart-release.yaml
- .github/workflows/check-codeql.yaml
- .github/workflows/check-helm-kics.yaml
- .github/workflows/check-nest-lint.yaml
- .github/workflows/check-nest-test-sonarcloud.yaml
Add reusable workflow to release helm charts.
[DBP-282](https://ticketsystem.dbildungscloud.de/browse/DBP-282)
> DBP-282-workflow-release-helm-chart

- .github/workflows/check-nest-test-sonarcloud.yaml
Make the workflow for sonarcloud compatible to the situation in the repositories schulportal-client and schulportal-testautomatisierung:
- Merge jobs into one, so that the package requirements are installed when sonarcloud runs
- Add option to skip the execution of jobs 
- Make deploy_stage input optional because it's not used in all repositories
- Option to change the timeout 
Merging the jobs can break the configuration which jobs are required, so this will be version 2.0.0
> DBP-332-sonarcloud

- .github/workflows/chart-release.yaml
> dbp-0000-bugfix-parse-ticketnr-into-lowercase

- .github/workflows/chart-release.yaml
- .github/workflows/check-trivy.yaml
- .github/workflows/image-publish-trivy.yaml
Checks if the tag_generation input is 'ticket_from_branch'.
If it is, it uses a regex to capture a ticket number from the branch name and assigns it to DOCKER_TAG.
If tag_generation is 'commit_hash', it sets DOCKER_TAG to a short SHA hash.
If none of the above conditions are met, it defaults DOCKER_TAG to 'latest'.
It then sets the DOCKER_TAG value as an environment variable for use in subsequent steps.
> Dbp 352 set the correct docker image in the helm chart for each spsh repository

- .github/workflows/chart-release.yaml
> DBP-0000-fix-missing-dollar

- .github/workflows/chart-release.yaml
> Dbp 394 version generation with timestamp

- .github/workflows/chart-release.yaml
- .github/workflows/image-publish-trivy.yaml
Better names for the inputs.
Breaking change -> Version 4.0.0
> DBP-352-input-naming-improvement

- .github/workflows/chart-release.yaml
> DBP-448-main-deployment-spsh-failure

- .github/workflows/release-image-and-helm-chart.yaml
- create a GHA to release a image and a Helm Chart, all that is needed are their names and the release_tag
- has been tested here: https://github.com/dBildungsplattform/schulportal-client/actions/runs/8189513750
> DBP-679-create-release-gha

- .github/workflows/chart-release.yaml
> Dbp 453 create redis db cluster available for session storage of spsh

- .github/workflows/image-publish-trivy.yaml
> Ops-6248-fix-conditional-input-check

- .github/workflows/auto-tag-release.yaml
Motivation:
The Update Semver Tags workflow is currently experiencing an issue where the semantic versioning (Semver) tags generated do not match the expected format
To do list:
Trigger the Update Semver Tags workflow.
Check the generated Semver tags.
Acceptance criteria (testable):
Semver tags are consistently generated in the format [major.minor.patch and major.minor and major]
> OPS-6298-Fix Senver generation

- .github/workflows/chart-release.yaml
> Ops 6635 image version chart release option

- .github/workflows/chart-release.yaml
Test runs: 
- https://github.com/dBildungsplattform/schulportal-client/actions/runs/10349875117/job/28645203304 (using default "")
- https://github.com/dBildungsplattform/dbp-moodle/actions/runs/10350023818/job/28645610102 (adding bitnami)
> Ops 6636 allow adding dependencies chart release

- .github/workflows/chart-release.yaml
This is supposed to mitigate the risk of getting this error and hopefully makes the Pipeline more stable. 
Run git config --global user.email "dbildungs-iam-server@dbildungsplattform.de"
[main 4aa415dd4] dbildungs-iam-server
1 file changed, 2 insertions(+), 2 deletions(-)
To https://github.com/dBildungsplattform/helm-charts-registry
! [rejected]            main -> main (fetch first)
error: failed to push some refs to 'https://github.com/dBildungsplattform/helm-charts-registry'
hint: Updates were rejected because the remote contains work that you do not
hint: have locally. This is usually caused by another repository pushing to
hint: the same ref. If you want to integrate the remote changes, use
hint: 'git pull' before pushing again.
hint: See the 'Note about fast-forwards' in 'git push …
> DBP-0000-improve-release-helm-chart-action

- .github/workflows/check-trivy.yaml
- .github/workflows/image-publish-trivy.yaml
> Test new trivy db

- .github/workflows/image-publish-trivy.yaml
- It is now possible to select **specified** as image_tag_generation and use a custom value as tag via **image_tag** input.
- After merge the new main state will be tagged as Version 7.1.0, 7.1, 7
> DBP-1179-allow-custom-image-name

- .github/workflows/chart-release.yaml
- .github/workflows/check-trivy.yaml
- .github/workflows/image-publish-trivy.yaml
The changes only leave more options to choose from and sets default values as provided per default in the trivy GHA. Therefore no changes in other repositories are needed and new tag with 7.* can get created
> DBP-1300-improve-trivy-action

- .github/workflows/image-publish-trivy.yaml
> DBP-0000-fix-code

- .github/workflows/chart-release.yaml
> DBP-1436-adding chart version output

- .github/workflows/check-nest-test-sonarcloud.yaml
https://github.com/dBildungsplattform/dbildungs-iam-server/actions/runs/17747154584
**Tag 7.3.0 will be created after merge**
> DBP-1657-Update Sonarqube GHA to 5.3.1
